### PR TITLE
Fix unit test and linting

### PR DESCRIPTION
**Pull request by RignonNoel**
### Changes proposed in this pull request:

* Adding Pycodestyle configs
* Correction of PEP8
* Correction of multiple tests and code associated if needed

### Opened discussion

There is a last problem with tests trying to import meals mockups. But the code make no sense when you compare the mock file in the repository and the logic of the import (number of columns is really different). I would like to discuss that with @guillaumep if possible to see what we do:

1. I could fix the import command if I know what we want
2. I could replace the mock file if we have one somewhere
3. We could just remove the tests related and add warning on the code if we have no knowledge on this part of the code

Output of the tests:
```
======================================================================
ERROR: setUpClass (souschef.datamigration.tests.ImportMemberMealsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/test/testcases.py", line 1042, in setUpClass
    cls.setUpTestData()
  File "/code/souschef/datamigration/tests.py", line 189, in setUpTestData
    call_command('importmeals', file='mock_meals.csv')
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/code/souschef/datamigration/management/commands/importmeals.py", line 69, in handle
    row[11 + (delivery_day * 10) + 1]
IndexError: list index out of range

```

### How to verify this change

1. Running pep8 tool like `pycodestyle .` (config file will be auto-detected thanks to `./setup.cfg`)
2. Running tests as described in the `DEVSETUP.md`
   - ie: `docker-compose run web python3 -Wa /code/souschef/manage.py test`
3. Checking all my commits of test resolution one-by-one, each of them contain a short amount of code and a large explanation of my finding with commit hashes related to the creation of the bug.

### CODE REVIEW

**Comment by guillaumep** [comment]
@RignonNoel It is quite unlikely we would have access to the files used by the Roulant to import the client's data from their previous system. I suspect that the importmeal command was modified during the import to fit actual data without the mock and the tests being adjusted.

Importing data into Sous-Chef for another meals-on-wheel (mow) company would most probably require writing a new import -- we can safely assume that their data format would be quite different (I've seen a mow that was using an Excel sheet).

All that to say we can safely comment or delete the test and update the command's code to mention no test exist.

**Comment by guillaumep** [comment]
Suggestions for future PRs:
- make the pycodestyle command executable from Docker, so the developer does not have to install Python and a virtualenv on his computer
- use black to format the files, and run the command to autoformat the whole repository (but see https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html so we can keep our Git history)

**Comment by RignonNoel** [comment]
> All that to say we can safely comment or delete the test and update the command's code to mention no test exist.

I share your opinion on the subject, so I removed the tests and added a warning message inside the command. Details will always be available via git history if one day somebody want to search on the subject

> Suggestions for future PRs:
>    - make the pycodestyle command executable from Docker, so the developer does not have to install Python and a virtualenv on his computer
>    - use black to format the files, and run the command to autoformat the whole repository (but see https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html so we can keep our Git history)

Thanks for the interesting proposition:

 - I created a `requirements-dev.txt` to keep the dev requirements clean and integrated the dev requirements inside the docker image
 - I integrated black into the project and reformatted all the codebase (I took the time to make sure we ignore the change in git blame)
 - I created a new github action, triggered on `push` AND `pull_request` to make sure we check `Black` format is respected
 - I also added Django test into the github action since the tests are on track now! 🎉 🚀

**Comment by guillaumep** [comment]
> * I also added Django test into the github action since the tests are on track now! 🎉 🚀

🎉 Cool! 🎉

Now I guess we "just" need to figure-out how to run the test DB using GitHub's actions. It's possible it's the timing issue described in the DEVSETUP file. On a local setup you can rerun the commands until the DB is ready, but on GitHub we'll need to figure-out a way to wait for the DB to be ready.

According to https://stackoverflow.com/questions/52322800/docker-compose-how-to-wait-for-other-service-to-be-ready and https://docs.docker.com/compose/startup-order/ we could use a "[wait-for-it.sh](https://github.com/vishnubob/wait-for-it/blob/master/wait-for-it.sh)" script which could solve our issues.

**Comment by RignonNoel** [comment]
@guillaumep Flake8 and Isort configured and integrated into the Github action workflow.

I also edited some commit descriptions as discussed together.

I think this PR is ready to merge if all is good for you.

N.B: Do !!**NOT**!! squash or rebase this PR into the master since the commit rev number are used to avoid `blame` on big trunk of changes made with isort and black. We should just merge the PR into master without prior transformation that could change the commit rev number.

**Review by guillaumep — APPROVED** [review]

**Pull request merged**
